In [3]:
import numpy as np
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
A = np.array([[1,2,3],
              [4,5,6]])

In [6]:
A.sum(axis=0)  #Column-wise

array([5, 7, 9])

In [7]:
A.sum(axis=1)  #Row-wise

array([ 6, 15])

In [8]:
A[A>3]

array([4, 5, 6])

In [10]:
A[A<5]

array([1, 2, 3, 4])

In [11]:
np.random.seed(42)

In [12]:
np.random.randn(5)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337])