In [1]:
l=[1,2,3]
print(l)

[1, 2, 3]


In [2]:
l[0]=10

In [3]:
print(l)

[10, 2, 3]


In [4]:
t=(1,2,3)
print(t)

(1, 2, 3)


In [5]:
t[0]=10
print(t)

TypeError: 'tuple' object does not support item assignment

In [6]:
#List Comprehension
squares=[i*i for i in range(5)]
print(squares)

[0, 1, 4, 9, 16]


In [7]:
def mean(y):
    return sum(y)/len(y)

print(mean(l))

5.0


In [8]:
#Lambda Functions
x=lambda z:z+10
print(x(10))

20


In [9]:
cubes=list(map(lambda x:x*x*x,[1,2,3]))
print(cubes)

[1, 8, 27]


In [10]:
#Used in Data Cleaning
filtered=list(filter(lambda x:x%5==0,[2,5,10,20,24]))
print(filtered)

[5, 10, 20]


In [11]:
import numpy as np
a=np.array([2,3,4])
print(a)

[2 3 4]


In [12]:
a.shape     #In ML wrong shape=Wrong model

(3,)

In [13]:
a.dtype      #In ML wrong dtype=performance loss

dtype('int64')

In [14]:
a[0:2]

array([2, 3])

In [15]:
#2D Array
m=np.array([[1,2,3,4,5],[2,4,6,8,10]])
print(m)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]


In [16]:
m[0,3]

np.int64(4)

In [17]:
#Broadcasting
a+10

array([12, 13, 14])

In [18]:
a=a*3
print(a)

[ 6  9 12]


In [19]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A@B

array([[19, 22],
       [43, 50]])

In [20]:
A.T

array([[1, 3],
       [2, 4]])

In [21]:
A.mean()

np.float64(2.5)

In [22]:
A.mean(axis=0)  #Vertical

array([2., 3.])

In [23]:
A.mean(axis=1) #Horizontal

array([1.5, 3.5])

In [24]:
A.std()

np.float64(1.118033988749895)